name: HTML

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Here is the deployment action
    - name: Upload from public_html via FTP denne virker.
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: nt1.unoeuro.com
        username: junoeuro.dk
        password: pch2gyb3
        server-dir: git/
        delete: true
